/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface) {
    await queryInterface.bulkInsert(
      'Orders',
      [
        {
          id: 1,
          name: 'Kelompok1',
          phone_number: '8745623',
          address: 'Jl. Mangga 3',
          transaction_date: new Date(2022, 8, 8, 14, 37, 8),
          sub_total: 60000,
          delivery_cost: 3000,
          total: 63000,
          note: '-',
          user_id: 1,
          status: 'Batal',
          no_order: 'OR-2022-9-8-1',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 2,
          name: 'Kelompok1',
          phone_number: '8745623',
          address: 'Jl. Mangga 3',
          transaction_date: new Date(2022, 9, 18, 18, 42, 11),
          sub_total: 29000,
          delivery_cost: 3000,
          total: 32000,
          note: '-',
          user_id: 1,
          status: 'Batal',
          no_order: 'OR-2022-10-18-2',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 3,
          name: 'Kelompok1',
          phone_number: '8745623',
          address: 'Jl. Mangga 3',
          transaction_date: new Date(2022, 9, 19, 5, 20, 19),
          sub_total: 25800,
          delivery_cost: 3000,
          total: 28800,
          note: '-',
          user_id: 1,
          status: 'Batal',
          no_order: 'OR-2022-10-19-3',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 4,
          name: 'Kelompok1',
          phone_number: '86536425',
          address: 'Jl. Mangga 3',
          transaction_date: new Date(2022, 9, 23, 15, 17, 2),
          sub_total: 60000,
          delivery_cost: 3000,
          total: 63000,
          note: '-',
          user_id: 1,
          status: 'Proses',
          no_order: 'OR-2022-10-23-7',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 5,
          name: 'Kelompok1',
          phone_number: '85364274',
          address: 'Jl. Mangga 3',
          transaction_date: new Date(2022, 9, 25, 7, 28, 34),
          sub_total: 27000,
          delivery_cost: 3000,
          total: 30000,
          note: '-',
          user_id: 1,
          status: 'Batal',
          no_order: 'OR-2022-10-25-9',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 6,
          name: 'Kelompok1',
          phone_number: '7632542',
          address: 'Jl. Mangga 3',
          transaction_date: new Date(2022, 9, 25, 10, 43, 7),
          sub_total: 30000,
          delivery_cost: 3000,
          total: 33000,
          note: '-',
          user_id: 1,
          status: 'Proses',
          no_order: 'OR-2022-10-25-10',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 7,
          name: 'Kelompok1',
          phone_number: '041431',
          address: 'Jl. Mangga 3',
          transaction_date: new Date(2022, 9, 25, 17, 0, 2),
          sub_total: 87000,
          delivery_cost: 3000,
          total: 90000,
          note: '-',
          user_id: 1,
          status: 'Batal',
          no_order: 'OR-2022-10-25-11',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {},
    );
  },

  async down() {
    return null;
  },
};
